In [2]:
#numpy 관련
import numpy as np

In [3]:
arr = np.arange(15)
print(arr, type(arr))
arr = arr.reshape(3,5) # 배열 재정의
print(arr, type(arr), arr.ndim) # 몇 차원인지?
print()
print(arr.shape, arr.size, arr.dtype.name)#크기(3 * 5), 자료 갯수, 자료형
print(arr.dtype.itemsize) # 데이터의 저장 공간 사이즈 : 4바이트

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'> 2

(3, 5) 15 int32
4


In [4]:
arr = np.arange(-5,5,0.5)
arr = arr.reshape(4, int(arr.size/4)) # 배열 재정의
print(arr)
arr1 = arr.flatten() #다차원을 1차원으로 변형
arr1.ndim

[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]]


1

In [5]:
# 기존의 파이썬 리스트로 array 생성
list_a = np.array([1,2,3])
list_b = np.array([[1,2,3],[4,5,6]])
print(list_a, type(list_a))
print(list_a.ndim, list_a.shape)
print()
print(list_b, type(list_b))
print(list_b.ndim, list_b.shape)

[1 2 3] <class 'numpy.ndarray'>
1 (3,)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
2 (2, 3)


In [15]:
a = np.zeros(5)
print(a)
b = np.zeros((2,3))
print(b)
print(np.zeros((5,2),dtype='i'))
print(np.zeros(5,dtype='U4'))
print(np.ones((2,3,4),dtype='i8'))
print(np.ones_like(b,dtype='f'))
print(np.empty((4,3)))
print(np.array([0,1,-1,0]),np.array([1,0,0,0]))


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
['' '' '' '' '']
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.04182483e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.89146896e-307 1.33664410e+160]
 [4.46537987e-090 6.09987504e+170 9.99374493e-048]
 [6.81444132e-038 3.99910963e+252 1.77502913e+160]]
[ 0  1 -1  0] [1 0 0 0]


In [16]:
x1 = np.array([-1.0, -2.0])
x2 = np.array([[5.0],[10.0],[15.0]])
x1 + x2

array([[ 4.,  3.],
       [ 9.,  8.],
       [14., 13.]])

In [29]:
#  numpy indexing, slicing, iterating
arr = np.arange(10) **2
print(arr)
print(arr[2])
print(arr[3:5])
arr[0:6:2] = -arr[0:6:2]
print(arr)
print(arr[::-1])
for i in arr:
    print(i,end='\t')
print()
arr = np.arange(1,21,1).reshape(4,5)
print(arr)
print(arr[3,4])
print()
print(arr[0:3, 1:]) 
print()
print(arr[1, ]) #1행출력
print(arr[-1, ]) # 마지막 행출력

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]
0	1	-4	9	-16	25	36	49	64	81	
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

[ 6  7  8  9 10]
[16 17 18 19 20]


In [32]:
# numpy 일반함수
# np.cos(), sin(), tanh(), exp()
arr = np.arange(0, 6, 1)
print(arr, np.cos(arr), np.exp(arr))

arr = np.arange(0.01, 1, 0.05)
print(np.log(arr))

[0 1 2 3 4 5] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]


In [37]:
arr1 = np.array([2,3,4])
arr2 = np.array([1,5,2])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))
print(np.sum(arr1))
print(np.random.choice(100,5)) # 0~100사이의 수 중에서 5개 출력
print(np.random.rand(2,3))  #2행 3열의 랜덤 값 리턴
print(np.random.randn(2,3)) #2행 3열의 랜덤 값 리턴(표준 정규분포)

#위치를 반환하는 함수 argmax, argmin
arr = np.array([6,2,3,1,4,5])
print(np.argmax(arr), ":", arr[np.argmax(arr)])

arr3 = np.array([[0.1, 0.8, 0.2], [0.3,0.2,0.5],[0.9,0.5,0.3]])
print(arr3)
print(np.argmax(arr3, axis = 1))
print(np.argmax(arr3, axis = 0))


[2 5 4]
[1 3 2]
9
[56  1  9  6 12]
[[0.73679735 0.98472542 0.58216049]
 [0.92724917 0.0591591  0.93334748]]
[[-0.12241144 -1.3856053   0.47455006]
 [ 0.86601251 -1.56302966  0.11140029]]
0 : 6
[[0.1 0.8 0.2]
 [0.3 0.2 0.5]
 [0.9 0.5 0.3]]
[1 2 0]
[2 0 1]


In [40]:
#기술 통계 함수
# count(), mean(), var(), std(), median(), max(), min(), percetile()
arr = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
               2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(arr))       #arr의 갯수
print(np.mean(arr))   #평균
print(np.var(arr))    #분산
print(np.std(arr))    #표준편차
print(np.max(arr),np.min(arr),np.median(arr)) #최댓값,최솟값,중앙값

print(np.percentile(arr,100))






26
4.8076923076923075
115.23224852071006
10.734628476137871
23 -24 5.0
23.0


In [45]:
#난수 발생과 카운팅
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [46]:
#데이터 순서를 바꾸는 방법
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 1 8 7 9 0 6 4 2 5]


In [55]:
#샘플링 : choice()
np.random.choice(arr,5,replace = False)  #셔플과 같은 결과
np.random.choice(10,3,replace = False)   #10개중 3개만 선택
np.random.choice(5,10) # 5개 숫자중 10개를 추출 중복 허용
np.random.choice(5,10, p=[0.1, 0, 0.3, 0.6, 0]) #선택확률 다르게

array([3, 2, 3, 3, 3, 3, 3, 0, 2, 0])

In [175]:
#randint() 정수 난수 발생                   최대값은 포함 x
np.random.randint(10, size =10) #(최대, 갯수) 최소, 갯수 생략 가능
np.random.randint(10, 20, size =10) # (최소, 최대, 갯수)
np.random.randint(10, 20, size=(3,5)) #3행 5열의 array 반환

array([[11, 19, 18, 19, 14],
       [11, 16, 11, 12, 13],
       [10, 14, 15, 13, 18]])

In [194]:
arr = np.arange(1,21)
print(arr)
print(arr[arr%3==0])
print(arr[arr%4==1])
print(arr[(arr%4==1) & (arr%3==0)])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [191]:
for i in arr:
    if i%3==0:
        print(i)
print()     
for i in arr:
    if i%4==1:
        print(i)
print()
for i in arr:
    if i%4==1 & i%3==0:
        print(i)

3
6
9
12
15
18

1
5
9
13
17

8
12
20
