In [2]:
#numpy 관련
import numpy as np

In [16]:
arr = np.arange(15)
print(arr, type(arr))
arr = arr.reshape(3,5) # 배열 재정의
print(arr, type(arr), arr.ndim) # 몇 차원인지?
print()
print(arr.shape, arr.size, arr.dtype.name)#크기(3 * 5), 자료 갯수, 자료형
print(arr.dtype.itemsize) # 데이터의 저장 공간 사이즈 : 4바이트

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'> 2

(3, 5) 15 int32
4


In [18]:
arr = np.arange(-5,5,0.5)
arr = arr.reshape(4, int(arr.size/4)) # 배열 재정의
print(arr)
arr1 = arr.flatten() #다차원을 1차원으로 변형
arr1.ndim

[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]]


1

In [23]:
# 기존의 파이썬 리스트로 array 생성
list_a = np.array([1,2,3])
list_b = np.array([[1,2,3],[4,5,6]])
print(list_a, type(list_a))
print(list_a.ndim, list_a.shape)
print()
print(list_b, type(list_b))
print(list_b.ndim, list_b.shape)

[1 2 3] <class 'numpy.ndarray'>
1 (3,)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
2 (2, 3)
