#### 머신러닝 개념(ML)

- 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법
- 지도학습(Supervised Learning) , 비지도학습(Un-Supervised Learning)
- 지도학습(분류, 회귀) , 비지도학습(클러스터링, 차원축소)

#### 머신러닝 용어(데이터의 형식 : DataFrame)
- 피처(feature) : 데이터의 일반 속성
- 레일블, 클래스, 타겟 값, 결정 값 : 정답데이터

In [1]:
import numpy as np
import pandas as pd

print('numpy version - ', np.__version__)
print('pandas version - ', pd.__version__)


numpy version -  1.20.3
pandas version -  1.3.4


In [2]:
import sklearn
from sklearn.datasets import load_iris

print('sklearn version - ', sklearn.__version__)

sklearn version -  0.24.2


In [4]:
iris = load_iris()
print("type - ", type(iris)) # Bunch 키-값 형식
print("keys - ", iris.keys())

type -  <class 'sklearn.utils.Bunch'>
keys -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
print("data - ", iris.data)
print("data type - ", type(iris.data))
print()
print("feature_names - ", iris.feature_names)
print("feature_names type - ", type(iris.feature_names))

data -  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

In [11]:
print("target - ", iris.target)
print("target type - ", type(iris.target)) # target = 레이블
print()
print("target_names - ", iris.target_names)
print("target_names type - ", type(iris.target_names)) # target = 레이블

print()
print("feature_names - ", iris.feature_names)
print("feature_names type - ", type(iris.feature_names)) # target = 레이블

target -  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
target type -  <class 'numpy.ndarray'>

target_names -  ['setosa' 'versicolor' 'virginica']
target_names type -  <class 'numpy.ndarray'>

feature_names -  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
feature_names type -  <class 'list'>


In [16]:
print('feature, target을 이용해서 데이터 프레임을 만들어보자 - ')
print()
iris_DF = pd.DataFrame(data = iris.data,
                       columns = iris.feature_names)
iris_DF['target'] = iris.target
iris_DF

feature, target을 이용해서 데이터 프레임을 만들어보자 - 



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

#### 지도학습  - 분류(classification)
- step 01. 데이터 분리(training data, test data) 학습데이터와 테스트데이터
- step 02. 학습데이터를 기반으로 ML 알고리즘을 적용해 학습 모델을 생성
- step 03. 테스트데이터를 기반으로 분류예측을 수행
- step 04. 모델의 성능평가


In [55]:
# 데이터 분류함수
from sklearn.model_selection import train_test_split
from sklearn.tree            import DecisionTreeClassifier
from sklearn.metrics         import accuracy_score

In [63]:
print('step 01. \n')
x_train, x_test ,y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    shuffle=True,
                                                    random_state=100)
#test_size 전체중 20프로를 테스트 데이터로

step 01. 



In [64]:
x_train.shape, x_test.shape ,y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [65]:
print('train data - ',x_train)
print('train data - ',y_train)

train data -  [[5.5 2.4 3.7 1. ]
 [5.7 2.8 4.1 1.3]
 [6.  2.2 5.  1.5]
 [4.8 3.  1.4 0.1]
 [5.4 3.9 1.3 0.4]
 [6.4 3.2 4.5 1.5]
 [5.1 3.8 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.4 5.6 2.4]
 [5.8 2.8 5.1 2.4]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [7.1 3.  5.9 2.1]
 [7.2 3.6 6.1 2.5]
 [4.9 3.6 1.4 0.1]
 [4.6 3.4 1.4 0.3]
 [5.  3.  1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.8 2.6 4.  1.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.3 1.7 0.5]
 [5.  3.2 1.2 0.2]
 [6.5 2.8 4.6 1.5]
 [7.9 3.8 6.4 2. ]
 [6.1 3.  4.9 1.8]
 [5.4 3.  4.5 1.5]
 [6.4 2.7 5.3 1.9]
 [5.7 2.9 4.2 1.3]
 [7.7 3.8 6.7 2.2]
 [6.5 3.2 5.1 2. ]
 [5.8 2.7 3.9 1.2]
 [4.6 3.6 1.  0.2]
 [6.9 3.1 5.4 2.1]
 [6.7 3.3 5.7 2.1]
 [6.3 2.8 5.1 1.5]
 [5.5 4.2 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.7 0.4]
 [5.5 3.5 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [6.9 3.1 4.9 1.5]
 [6.5 3.  5.8 2.2]
 [6.7 3.3 5.7 2.5]
 [6.1 2.6 5.6 1.4]
 [5.4 3.7 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [5.9 3.2 4.8 1.8]
 [4.6 3.1 1.5 0.2]
 [6.8 2.8 4.8 1.4]
 [4.9 2.4 3.3 1. ]
 [6.2 2.8 4.8 1.8

In [66]:
print('train data - ',x_test)
print('train data - ',y_test) # 셔플의 중요성 

train data -  [[6.4 2.8 5.6 2.1]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [5.7 4.4 1.5 0.4]
 [6.3 2.7 4.9 1.8]
 [7.7 3.  6.1 2.3]
 [5.2 4.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [6.5 3.  5.5 1.8]
 [4.8 3.  1.4 0.3]
 [5.  3.5 1.3 0.3]
 [6.4 3.2 5.3 2.3]
 [5.  3.4 1.6 0.4]
 [5.2 3.4 1.4 0.2]
 [6.7 3.  5.2 2.3]
 [6.2 2.9 4.3 1.3]
 [6.  2.2 4.  1. ]
 [6.7 3.  5.  1.7]
 [7.7 2.8 6.7 2. ]
 [6.8 3.  5.5 2.1]
 [7.2 3.2 6.  1.8]
 [5.4 3.4 1.5 0.4]
 [6.3 2.5 5.  1.9]
 [4.7 3.2 1.6 0.2]
 [5.6 2.5 3.9 1.1]
 [5.9 3.  5.1 1.8]
 [6.6 3.  4.4 1.4]
 [5.4 3.4 1.7 0.2]
 [6.1 2.8 4.7 1.2]
 [6.9 3.2 5.7 2.3]]
train data -  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]


In [67]:
print('step 02. \n')

iris_DF_model = DecisionTreeClassifier()
iris_DF_model.fit(x_train, y_train) #학습데이터만

step 02. 



DecisionTreeClassifier()

In [68]:
print('step 03. predict() \n')

y_pred = iris_DF_model.predict(x_test) # 예측결과를 리턴
print('y_test - ',y_test) # 정답
print('y_pred - ',y_pred) # 결과

step 03. predict() 

y_test -  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]
y_pred -  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2]


In [69]:
print('step 04. 예측정확도 - \n')

print('acc - ',accuracy_score(y_test, y_pred))

step 04. 예측정확도 - 

acc -  0.9666666666666667


In [81]:
print('데이터 프레임 형식에서 학습데이터와 테스트데이터를 분리한다면? - \n')

print('iloc() 이영해서 피처와 타겟을 추출한다면 - ')
iris_feature_FD = iris_DF.iloc[:,0:4]
iris_target_FD = iris_DF.iloc[:, 4]
display(iris_feature_FD)
display(iris_target_FD)

데이터 프레임 형식에서 학습데이터와 테스트데이터를 분리한다면? - 

iloc() 이영해서 피처와 타겟을 추출한다면 - 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [82]:
print('step 01. \n')
x_train, x_test ,y_train, y_test = train_test_split(iris_feature_FD,
                                                    iris_target_FD,
                                                    test_size=0.2,
                                                    shuffle=True,
                                                    random_state=100)

step 01. 



In [83]:
iris_DF_model = DecisionTreeClassifier()
iris_DF_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [85]:
y_pred = iris_DF_model.predict(x_test) # 예측결과를 리턴
print('y_test - ',y_test) # 정답
print('y_pred - ',y_pred, type(y_pred)) # 결과

y_test -  128    2
11     0
118    2
15     0
123    2
135    2
32     0
1      0
116    2
45     0
40     0
115    2
26     0
28     0
145    2
97     1
62     1
77     1
122    2
112    2
125    2
31     0
146    2
29     0
69     1
149    2
75     1
20     0
73     1
120    2
Name: target, dtype: int32
y_pred -  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2] <class 'numpy.ndarray'>


In [86]:
print('acc - ',accuracy_score(y_test, y_pred))

acc -  0.9666666666666667


#### 교차검증(croos validation)
- 과적합(overffiting)을 방지하기위한 방법
- 데이터의 편중을 막기위해서
- kFold 방식

In [105]:
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score, cross_validate

# KFold 셔플 없음,   StratifiedKFold 셔플 있음

In [106]:
fold_iris = load_iris()

features = fold_iris.data
lable    = fold_iris.target

In [107]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [108]:
lable

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
print('5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자 - ')
cv_acc = []
kfold = KFold(n_splits=5)

fold_dct_model = DecisionTreeClassifier()

for train_idx , test_idx in kfold.split(features):
    #print('train idx - ', train_idx)
    #print('test idx  - ', test_idx)
    x_train, x_val = features[train_idx], features[test_idx]
    y_train, y_val = lable[train_idx], lable[test_idx]
    #print('x_train - ', x_train)
    #print('x_val  - ', x_val)
    fold_dct_model.fit(x_train, y_train)
    
    fold_pred = fold_dct_model.predict(x_val)
    acc = accuracy_score(y_val, fold_pred)
    print('acc - ',acc)
    cv_acc.append(acc)

print('교차검증 평균 정확도 - ', np.mean(cv_acc))

5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자 - 
acc -  1.0
acc -  1.0
acc -  0.9
acc -  0.9333333333333333
acc -  0.7333333333333333
교차검증 평균 정확도 -  0.9133333333333333


In [166]:
print('기존 KFold 방식의 문제점 확인 - \n')

fold_iris_frm = pd.DataFrame(data    = fold_iris.data,
                             columns = fold_iris.feature_names
                            )
fold_iris_frm['target'] = fold_iris.target
fold_iris_frm

기존 KFold 방식의 문제점 확인 - 



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [167]:
fold_iris_frm['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [175]:
bad_fold_iris = KFold(n_splits = 3)
n_iter = 0

fold_dct_model = DecisionTreeClassifier()
    
for train_idx , test_idx in bad_fold_iris.split(fold_iris.data):
    n_iter+=1
    
    x_train, x_val = fold_iris.data[train_idx], fold_iris.data[test_idx]
    y_train, y_val = fold_iris.target[train_idx], fold_iris.target[test_idx]
    
    lable_train  = fold_iris_frm['target'].iloc[train_idx]
    lable_val    = fold_iris_frm['target'].iloc[test_idx]
    
    #print('교차검증 횟수 - ', n_iter)
    #print('학습 레이블 데이터 분포 - ', lable_train.iloc[:])
    #print('검증 레이블 데이터 분포 - ', lable_val)
    
    fold_dct_model.fit(x_train, y_train)
    
    fold_pred = fold_dct_model.predict(x_val)
    acc = accuracy_score(y_val, fold_pred)
    print('acc - ',acc)
    cv_acc.append(acc)

print('교차검증 평균 정확도 - ', np.mean(cv_acc))

acc -  0.0
acc -  0.0
acc -  0.0
교차검증 평균 정확도 -  0.3952380952380953


#### 연습
- 아이리스 데이터를 이용하여 StratifiedKFold 교차검증을 진행해 보자
- random_state = 200
- StratifiedKFold(3, 5) 평균 정확도 확인

In [128]:
test_iris = load_iris()
test_DF = pd.DataFrame(data = test_iris.data,
                       columns = test_iris.feature_names)
test_DF['target'] = test_iris.target
test_DF

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [176]:
cv_acc = []
count=0
St_KFold = StratifiedKFold(n_splits=5)
fold_dct_model = DecisionTreeClassifier(random_state = 200)

for train_idx , test_idx in St_KFold.split(test_iris.data, test_iris.target):
    x_train, x_val = test_iris.data[train_idx], test_iris.data[test_idx]
    y_train, y_val = test_iris.target[train_idx], test_iris.target[test_idx]
    count += 1
    fold_dct_model.fit(x_train, y_train)
    fold_pred = fold_dct_model.predict(x_val)
    acc = accuracy_score(y_val, fold_pred)
    
    print(f'검증횟수{count}, 교차검증 정확도 {acc}')
    cv_acc.append(acc)

print('교차검증 평균 정확도 - ', np.mean(cv_acc))

검증횟수1, 교차검증 정확도 0.9666666666666667
검증횟수2, 교차검증 정확도 0.9666666666666667
검증횟수3, 교차검증 정확도 0.9
검증횟수4, 교차검증 정확도 1.0
검증횟수5, 교차검증 정확도 1.0
교차검증 평균 정확도 -  0.9666666666666668
